using System.Globalization;
using System.Text;
using AudioSwitch.Core.Models;

namespace AudioSwitch.Core.Services;

// Builds Equalizer APO config-file text from our 10-band EqualizerComponent model.
//
// APO config syntax we emit:
//   Device: <friendly name>
//   GraphicEQ: 31 -3.0; 62 -2.5; 125 0.0; ...
//
// Notes:
// - GraphicEQ is APO's built-in N-band equalizer; the band list is "freq gain"
//   pairs separated by semicolons. Frequencies are integers (Hz), gains are
//   floats (dB). APO interpolates between bands, so any band count works —
//   we just emit whatever the EqualizerComponent has.
// - Numbers MUST use invariant culture (period decimal separator). APO doesn't
//   parse comma decimals; a German user without invariant formatting would get
//   silent EQ failure.
// - The Device: directive scopes everything until the next Device: line. We
//   write one block per (device, equalizer) pair so multiple endpoints can have
//   different EQs in one config file without leaking between them.
// - Header comment marks the file as ours so users know not to hand-edit it
//   (and so a future "uninstall my APO config" feature can find what to remove).
public static class ApoConfigBuilder
{
    public const string GeneratedHeader = "# Generated by AudioSwitch — do not edit by hand.";

    public static string BuildGraphicEqLine(IReadOnlyList<EqualizerBand> bands)
    {
        if (bands.Count == 0) return "GraphicEQ: ";
        var pairs = bands.Select(b =>
            $"{b.Frequency} {b.Gain.ToString("0.0", CultureInfo.InvariantCulture)}");
        return $"GraphicEQ: {string.Join("; ", pairs)}";
    }

    public static string BuildDeviceBlock(string deviceName, IReadOnlyList<EqualizerBand> bands)
    {
        var sb = new StringBuilder();
        sb.Append("Device: ").AppendLine(deviceName);
        sb.AppendLine(BuildGraphicEqLine(bands));
        return sb.ToString();
    }

    public static string BuildConfig(IReadOnlyList<ApoDeviceEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedHeader);
        sb.AppendLine();
        foreach (var entry in entries)
        {
            sb.AppendLine(BuildDeviceBlock(entry.DeviceName, entry.Bands));
        }
        return sb.ToString();
    }
}

public sealed record ApoDeviceEntry(string DeviceName, IReadOnlyList<EqualizerBand> Bands);
